### PR TITLE
Included es.lproj for the translation of the tweak into Spanish

### PR DESCRIPTION
**Pull request by longopy**
Hello!
I could see that the localization support has been enabled and I decided to add the Spanish language.
Regards!

### CODE REVIEW

**Comment by asdfzxcvbn** [comment]
is this google translate? i see some abnormalities here

**Comment by longopy** [comment]
> is this google translate? i see some abnormalities here

No. I made some changes to make it make more sense in natural language. For example in the word "Fallback"

**Comment by asdfzxcvbn** [comment]
i mean, i see both "ajuste" and "tweak" being used, i would prefer using only 1 word

**Comment by asdfzxcvbn** [comment]
also, playlist is still "playlist" in spanish

**Comment by longopy** [comment]
> also, playlist is still "playlist" in spanish

playlist in Spanish is: "lista de reproducción", but we can keep playlist if you wish.

**Comment by asdfzxcvbn** [comment]
> > also, playlist is still "playlist" in spanish
> 
> playlist in Spanish is: "lista de reproducción", but we can keep playlist if you wish.

whatever you think is best. i like "playlist" but at least address the other issue, thanks

**Comment by longopy** [comment]
> > > also, playlist is still "playlist" in spanish
> > 
> > 
> > playlist in Spanish is: "lista de reproducción", but we can keep playlist if you wish.
> 
> whatever you think is best. i like "playlist" but at least address the other issue, thanks

I prefer "lista de reproducción", "playlist" is an anglicism.
But I have solved the other problem, so that we can use only one word to refer to the modification: "tweak".

**Comment by asdfzxcvbn** [comment]
thanks!

**Pull request merged**
