### PR TITLE
Add entitlements and privacy permissions

### PR DESCRIPTION
**Pull request by postulat3**
Fix a missing entitlements/privacy permissions error when installing through AltStore 2.0

### CODE REVIEW

**Comment by asdfzxcvbn** [comment]
can you send a pic of the error and it being resolved with your modifications? i remember `privacy` is not a dictionary (despite what altstore docs say) and you can see it as a list in other altstore sources

**Comment by postulat3** [comment]
Original warning:
IMG_1267
Clicking on "View Permissions":
IMG_1269

After adding the entitlements (my modifications), it goes straight to this screen. Scrolling to the bottom and clicking "Approve" installs the app with no further interaction
IMG_1270

`privacy` has to be a dictionary if it isn't empty, otherwise altstore doesn't allow the source to be added (consistent with the docs)

**Comment by asdfzxcvbn** [comment]
they finally fixed their docs !!!!!!!!!

how amazing! this one time change wont fix anything though, im going to fix this directly in our update script. thanks for the news, though!

**Comment by whoeevee** [comment]
the pr is very demure

**Pull request closed without merging**
