### PR TITLE
Add brazil loc

### PR DESCRIPTION
**Pull request by emal0n**

### CODE REVIEW

**Comment by kyotometus** [comment]
The observations below show terms that use a more "globalized" vocabulary or are not a good translation into PT-BR, favoring the use of words similar to English, without prioritizing the use of more appropriate or common terms in Brazilian Portuguese:

```txt
patching = "Patcheando"
lyrics = "Lyrics"
customization = "Customização"
reset_data = "Resetar dados"
romanized_lyrics = "Lyrics romanizadas"
fallback_attribute = "Fallback"
musixmatch_user_token = "Token de usuário Musixmatch"
musixmatch_language = "Idioma das Lyrics do Musixmatch"
```

You could easily change to:

```txt
patching = "Aplicando correção"
lyrics = "Letras"
customization = "Personalização"
reset_data = "Redefinir dados"
romanized_lyrics = "Letras transliteradas"
fallback_attribute = "Recurso de contingência"
musixmatch_user_token = "Token de usuário do Musixmatch"
musixmatch_language = "Idioma das letras do Musixmatch"
```

**Comment by emal0n** [comment]
oh, ok

**Comment by emal0n** [comment]
Check now

**Comment by kyotometus** [comment]
LGTM!

**Comment by emal0n** [comment]
> LGTM! 

nice

**Comment by asdfzxcvbn** [comment]
incorrect folder name, change it to `pt-BR.lproj` please

**Comment by emal0n** [comment]
> incorrect folder name, change it to `pt-BR.lproj` please

oh, sorry

**Comment by emal0n** [comment]
Done.

**Pull request merged**
