### PR TITLE
Correct Vietnamese translation

### PR DESCRIPTION
**Pull request by Richard-NDC**
ok so i correct it as you said and correct some part easier to understand

### CODE REVIEW

**Comment by asdfzxcvbn** [comment]
is it really easier to understand? some of the titles seem too long

**Comment by Richard-NDC** [comment]
> is it really easier to understand? some of the titles seem too long

yes, it is

**Comment by asdfzxcvbn** [comment]
regarding "Ngôn ngữ sử dụng để dịch lời bài hát từ Musixmatch" ,, this looks an awfully bit long, isnt there a way to make it more concise?

**Comment by asdfzxcvbn** [comment]
alright looks good, could you just add a new string? see here: https://github.com/whoeevee/EeveeSpotify/blob/eeaa55e4fd32b0660794873bc81073efdfffedab/layout/Library/Application%20Support/EeveeSpotify.bundle/en.lproj/Localizable.strings#L105-L107

**Comment by Richard-NDC** [comment]
> alright looks good, could you just add a new string? see here:
> 
> https://github.com/whoeevee/EeveeSpotify/blob/eeaa55e4fd32b0660794873bc81073efdfffedab/layout/Library/Application%20Support/EeveeSpotify.bundle/en.lproj/Localizable.strings#L105-L107

ok i will add it

**Comment by Richard-NDC** [comment]
> alright looks good, could you just add a new string? see here:
> 
> https://github.com/whoeevee/EeveeSpotify/blob/eeaa55e4fd32b0660794873bc81073efdfffedab/layout/Library/Application%20Support/EeveeSpotify.bundle/en.lproj/Localizable.strings#L105-L107

done

**Comment by asdfzxcvbn** [comment]
thanks

**Pull request merged**
