### PR TITLE
Add View Contributors page

### PR DESCRIPTION
**Pull request by ElliotCHEN37**

### CODE REVIEW

**Comment by ElliotCHEN37** [comment]
> Any preview?

still w.i.p
i'll release the preview when it's ready

**Comment by ElliotCHEN37** [comment]
Currently sorted manually by me according to GitHub Contributor page. 
Perhaps I'll make it sorts and lists automatically

**Comment by asdfzxcvbn** [comment]
thanks for the idea and commits, but eevee has decided that he will write his own

**Comment by ElliotCHEN37** [comment]
Everything should work now (including auto sorting)

**Pull request closed without merging**
