### PR TITLE
Turkish Loc updated

### PR DESCRIPTION
**Pull request by gototheskinny**
latest update reverted almost all of the words to english. i dont know why.. i hope this fixes it. cant really try too bc there's no building option in the actions, sorry ;(

### CODE REVIEW

**Comment by whoeevee** [comment]
starting from version 5.7, EeveeSpotify uses an English localization for missing strings
if you see it, feel free to open a pr like this one

**Comment by ElliotCHEN37** [comment]
@gototheskinny Please do not use double quotes within double quotes (please use single quotes or non-English double quotes), because this will cause JSON parsing errors and directly lead to compilation failure.
This was fixed in #516

**Comment by yodaluca23** [comment]
> @gototheskinny Please do not use double quotes within double quotes (please use single quotes or non-English double quotes), because this will cause JSON parsing errors and directly lead to compilation failure.

Can you not use escape characters in JSON? ```\"```?

**Comment by ElliotCHEN37** [comment]
> > @gototheskinny Please do not use double quotes within double quotes (please use single quotes or non-English double quotes), because this will cause JSON parsing errors and directly lead to compilation failure.
> 
> Can you not use escape characters in JSON? `\"`?

nice

**Comment by gototheskinny** [comment]
> @gototheskinny Please do not use double quotes within double quotes (please use single quotes or non-English double quotes), because this will cause JSON parsing errors and directly lead to compilation failure.
> 
> This was fixed in #516 

Oh thank you for letting me know about it.

**Pull request merged**
