### PR TITLE
Edit and correct some part of Vietnamese translation

### PR DESCRIPTION
**Pull request by Richard-NDC**

### CODE REVIEW

**Comment by asdfzxcvbn** [comment]
what's "bẻ khóa" ?

**Comment by Richard-NDC** [comment]
> what's "bẻ khóa" ?

it’s mean crack but if you translate “patching” is “bản vá” somebody may misunderstand about it

**Comment by Richard-NDC** [comment]
> what's "bẻ khóa" ?

my main language is Vietnamese, so i’m just translate it for what we commonly call

**Comment by asdfzxcvbn** [comment]
> > what's "bẻ khóa" ?
> 
> my main language is Vietnamese, so i’m just translate it for what we commonly call

okay but it's not correct, you said "Bản vá" is "Patching" (correct), and (translated) "Cài đặt bẻ khóa" means "Installing jailbreak" which is incorrect

it really doesnt feel like this should be merged, running the strings through a translator, the existing localization already feels correct

**Comment by Richard-NDC** [comment]
> > > what's "bẻ khóa" ?
> > 
> > 
> > my main language is Vietnamese, so i’m just translate it for what we commonly call
> 
> okay but it's not correct, you said "Bản vá" is "Patching" (correct), and (translated) "Cài đặt bẻ khóa" means "Installing jailbreak" which is incorrect
> 
> it really doesnt feel like this should be merged, running the strings through a translator, the existing localization already feels correct

no, “Cài đặt bẻ khoá” it mean “Crack settings” not “Installing Jailbreak”

**Pull request closed without merging**
