### PR TITLE
some updates~~~

### PR DESCRIPTION
**Pull request by ElliotCHEN37**

### CODE REVIEW

**Comment by ElliotCHEN37** [comment]
1. zh-TW trans update
2. added petitlyrics to readme
3. fix tr.lproj which was causing an issue when building

**Comment by yodaluca23** [comment]
It's backslash ```\``` not forward slash.

**Comment by ElliotCHEN37** [comment]
> It's backslash `\` not forward slash.

ok

**Comment by ElliotCHEN37** [comment]
> It's backslash `\` not forward slash.

Thanks for the correction

**Pull request merged**
